#!/bin/bash
# Reads .env from repo root and writes ispy/ispy/Secrets.swift
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/ispy/ispy/Secrets.swift"

if [ ! -f "$ENV_FILE" ]; then
  echo "warning: .env not found at $ENV_FILE — Secrets.swift not updated"
  exit 0
fi

source "$ENV_FILE"

cat > "$OUT" << SWIFT
// Auto-generated by scripts/generate-secrets.sh — do not edit manually
enum Secrets {
    static let hfToken = "${HF_TOKEN}"
}
SWIFT

echo "Secrets.swift updated."
